### ISSUE TITLE
Library not downloadable from https://maven.skaggsm.com/releases

### ISSUE THREAD

**Issue by GeheimagentNr1** [magneticflux-/java-mumble-link#9]
Gradle is showing the error `Could not find com.skaggsm:java-mumble-link:0.2.6.`, when trying to download the java-mumble-link library.  
  
part in the gradle.properties:  
```
java_mumble_link_version=0.2.6
```
  
parts in the build.gradle:

```
repositories {
    maven {
        name = "skaggsm"
        url = uri("https://maven.skaggsm.com/releases")
    }
}
dependencies {
    implementation("com.skaggsm:java-mumble-link:${java_mumble_link_version}") {
        exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
        exclude group: 'net.java.dev.jna'
    }
}
```

**Comment by magneticflux-** [comment]
Whoops, I forgot to restart my Maven webserver after rearranging hosts last week! It should be online now, sorry about the disruption.

**Comment by GeheimagentNr1** [comment]
No problem.  
Thank you for the quick fix. It is working now.
